// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testutil.proto

#include "testutil.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace rome {
namespace testutil {
PROTOBUF_CONSTEXPR RdmaChannelTestProto::RdmaChannelTestProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct RdmaChannelTestProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RdmaChannelTestProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RdmaChannelTestProtoDefaultTypeInternal() {}
  union {
    RdmaChannelTestProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RdmaChannelTestProtoDefaultTypeInternal _RdmaChannelTestProto_default_instance_;
PROTOBUF_CONSTEXPR ConnectionManagerTestProto::ConnectionManagerTestProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct ConnectionManagerTestProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConnectionManagerTestProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConnectionManagerTestProtoDefaultTypeInternal() {}
  union {
    ConnectionManagerTestProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConnectionManagerTestProtoDefaultTypeInternal _ConnectionManagerTestProto_default_instance_;
}  // namespace testutil
}  // namespace rome
static ::_pb::Metadata file_level_metadata_testutil_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_testutil_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_testutil_2eproto = nullptr;

const uint32_t TableStruct_testutil_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::rome::testutil::RdmaChannelTestProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::rome::testutil::RdmaChannelTestProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rome::testutil::RdmaChannelTestProto, _impl_.message_),
  0,
  PROTOBUF_FIELD_OFFSET(::rome::testutil::ConnectionManagerTestProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::rome::testutil::ConnectionManagerTestProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rome::testutil::ConnectionManagerTestProto, _impl_.message_),
  0,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, -1, sizeof(::rome::testutil::RdmaChannelTestProto)},
  { 8, 15, -1, sizeof(::rome::testutil::ConnectionManagerTestProto)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::rome::testutil::_RdmaChannelTestProto_default_instance_._instance,
  &::rome::testutil::_ConnectionManagerTestProto_default_instance_._instance,
};

const char descriptor_table_protodef_testutil_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016testutil.proto\022\rrome.testutil\"\'\n\024RdmaC"
  "hannelTestProto\022\017\n\007message\030\001 \001(\t\"-\n\032Conn"
  "ectionManagerTestProto\022\017\n\007message\030\001 \001(\t"
  ;
static ::_pbi::once_flag descriptor_table_testutil_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_testutil_2eproto = {
    false, false, 119, descriptor_table_protodef_testutil_2eproto,
    "testutil.proto",
    &descriptor_table_testutil_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_testutil_2eproto::offsets,
    file_level_metadata_testutil_2eproto, file_level_enum_descriptors_testutil_2eproto,
    file_level_service_descriptors_testutil_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_testutil_2eproto_getter() {
  return &descriptor_table_testutil_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_testutil_2eproto(&descriptor_table_testutil_2eproto);
namespace rome {
namespace testutil {

// ===================================================================

class RdmaChannelTestProto::_Internal {
 public:
  using HasBits = decltype(std::declval<RdmaChannelTestProto>()._impl_._has_bits_);
  static void set_has_message(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

RdmaChannelTestProto::RdmaChannelTestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rome.testutil.RdmaChannelTestProto)
}
RdmaChannelTestProto::RdmaChannelTestProto(const RdmaChannelTestProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RdmaChannelTestProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.message_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_message()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:rome.testutil.RdmaChannelTestProto)
}

inline void RdmaChannelTestProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.message_){}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RdmaChannelTestProto::~RdmaChannelTestProto() {
  // @@protoc_insertion_point(destructor:rome.testutil.RdmaChannelTestProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RdmaChannelTestProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
}

void RdmaChannelTestProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RdmaChannelTestProto::Clear() {
// @@protoc_insertion_point(message_clear_start:rome.testutil.RdmaChannelTestProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.message_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RdmaChannelTestProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string message = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "rome.testutil.RdmaChannelTestProto.message");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RdmaChannelTestProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rome.testutil.RdmaChannelTestProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string message = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "rome.testutil.RdmaChannelTestProto.message");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rome.testutil.RdmaChannelTestProto)
  return target;
}

size_t RdmaChannelTestProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rome.testutil.RdmaChannelTestProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string message = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RdmaChannelTestProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RdmaChannelTestProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RdmaChannelTestProto::GetClassData() const { return &_class_data_; }


void RdmaChannelTestProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RdmaChannelTestProto*>(&to_msg);
  auto& from = static_cast<const RdmaChannelTestProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rome.testutil.RdmaChannelTestProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_message()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RdmaChannelTestProto::CopyFrom(const RdmaChannelTestProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rome.testutil.RdmaChannelTestProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RdmaChannelTestProto::IsInitialized() const {
  return true;
}

void RdmaChannelTestProto::InternalSwap(RdmaChannelTestProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata RdmaChannelTestProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_testutil_2eproto_getter, &descriptor_table_testutil_2eproto_once,
      file_level_metadata_testutil_2eproto[0]);
}

// ===================================================================

class ConnectionManagerTestProto::_Internal {
 public:
  using HasBits = decltype(std::declval<ConnectionManagerTestProto>()._impl_._has_bits_);
  static void set_has_message(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

ConnectionManagerTestProto::ConnectionManagerTestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rome.testutil.ConnectionManagerTestProto)
}
ConnectionManagerTestProto::ConnectionManagerTestProto(const ConnectionManagerTestProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ConnectionManagerTestProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.message_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_message()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:rome.testutil.ConnectionManagerTestProto)
}

inline void ConnectionManagerTestProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.message_){}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ConnectionManagerTestProto::~ConnectionManagerTestProto() {
  // @@protoc_insertion_point(destructor:rome.testutil.ConnectionManagerTestProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ConnectionManagerTestProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
}

void ConnectionManagerTestProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ConnectionManagerTestProto::Clear() {
// @@protoc_insertion_point(message_clear_start:rome.testutil.ConnectionManagerTestProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.message_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ConnectionManagerTestProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string message = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "rome.testutil.ConnectionManagerTestProto.message");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ConnectionManagerTestProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rome.testutil.ConnectionManagerTestProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string message = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "rome.testutil.ConnectionManagerTestProto.message");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rome.testutil.ConnectionManagerTestProto)
  return target;
}

size_t ConnectionManagerTestProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rome.testutil.ConnectionManagerTestProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string message = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ConnectionManagerTestProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ConnectionManagerTestProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ConnectionManagerTestProto::GetClassData() const { return &_class_data_; }


void ConnectionManagerTestProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ConnectionManagerTestProto*>(&to_msg);
  auto& from = static_cast<const ConnectionManagerTestProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rome.testutil.ConnectionManagerTestProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_message()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ConnectionManagerTestProto::CopyFrom(const ConnectionManagerTestProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rome.testutil.ConnectionManagerTestProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConnectionManagerTestProto::IsInitialized() const {
  return true;
}

void ConnectionManagerTestProto::InternalSwap(ConnectionManagerTestProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata ConnectionManagerTestProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_testutil_2eproto_getter, &descriptor_table_testutil_2eproto_once,
      file_level_metadata_testutil_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace testutil
}  // namespace rome
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::rome::testutil::RdmaChannelTestProto*
Arena::CreateMaybeMessage< ::rome::testutil::RdmaChannelTestProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rome::testutil::RdmaChannelTestProto >(arena);
}
template<> PROTOBUF_NOINLINE ::rome::testutil::ConnectionManagerTestProto*
Arena::CreateMaybeMessage< ::rome::testutil::ConnectionManagerTestProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rome::testutil::ConnectionManagerTestProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
